version: '3.8'
services:
  postgres:
    container_name: postgres-sql-bn
    image: postgres:latest
    environment:
      POSTGRES_USER: userbn
      POSTGRES_PASSWORD: start
      POSTGRES_DB: book_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bn
    image: maildev/maildev
    ports:
      - "2080:1080"
      - "1025:1025"
  pgadmin:
    container_name: pgadmin-bn
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@dev.com
      PGADMIN_DEFAULT_PASSWORD: start
    ports:
      - "5050:80"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local